baseurl = "http://joshua.poehls.me"
languageCode = "en-us"
title = "joshua poehls | silent thought"
copyright = "Copyright (c) 2014-2015 Joshua Poehls. All rights reserved."
metadataFormat = "yaml"

paginate = 10
paginatePath = "page"

[permalinks]
	post = "/:year/:month/:slug"

[author]
	name = "Joshua Poehls"

[indexes]
	tag = "tags"