baseurl = "http://joshua.poehls.me"
languageCode = "en-us"
title = "joshua poehls | silent thoughts"
copyright = "Copyright (c) 2014-2017 Joshua Poehls. All rights reserved."
metadataFormat = "yaml"

paginate = 10
paginatePath = "page"

footnoteAnchorPrefix = "fn"
footnoteReturnLinkContents = "↩"

disableKinds = ["404"]

[outputFormats]
[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"

[permalinks]
	post = "/:year/:slug"

[author]
	name = "Joshua Poehls"

[taxonomies]
	tag = "tags"
	series = "series"