[[thought]]
translation = "nasb"
revision = "NASB 2020"
reference = "Job 5:17"
date = '24 Jun 2023'
emoji = "😔"
text = '''
NASB uses `happy` in Job 5:17 but has a cross-reference to Psalm 94:12 where `blessed` is used for the same Hebrew word and context.
CSB consistently translates both as `happy`; LSB has both as `blessed`.
'''

[[thought]]
translation = "lsb"
reference = "Psalm 2:1"
date = '6 Apr 2023'
text = '''
Uses “and the peoples meditate on a vain thing” clearly showing the connection to Psalm 1:2 “in his law he meditates day and night” where the same Hebrew word is in both cases.

These Psalms contrast the meditations of the righteous and the wicked. Kudos to Scott Aniol for making this connection in his talk [Musing on God’s Music](https://youtu.be/MRujkRSvS2U) at the Covenant Baptist Theological Seminary conference 2023.
'''

[[thought]]
translation = "lsb"
reference = "Hosea 13:14a"
date = '7 Apr 2023'
emoji = "👍"
text = '''
Love how it translates Hosea 13:14a as a rhetorical question. ESV and NET also does this, but not as elegantly. CSB flops here.
'''

[[thought]]
translation = "lsb"
reference = "Zechariah 9:11"
date = '10 Apr 2023'
emoji = "🤔"
text = '''
ESV translates as “my covenant”. NASB also gets translates as “my”. CSB and LSB translate as “your covenant”. NET as “our covenant”.
'''

[[thought]]
translation = "esv"
revision = "ESV 2016"
reference = "Zechariah 9:11"
date = '10 Apr 2023'
emoji = "🤔"
text = '''
ESV translates Zech 9:11 as "...**my** covenant." NASB also gets translates as "my." CSB and LSB translate as "**your** covenant." NET as "**our** covenant."
'''

[[thought]]
translation = "esv"
revision = "ESV 2016"
reference = "Matthew 16:27"
date = '5 Oct 2023'
text = '''
ESV lacks OT cross-references for Matt 16:27. LSB references Ps 62:12 and Prov 24:12 in addition to NT references.
'''

[[thought]]
translation = "csb"
reference = "1 Corinthians 7"
date = '1 Feb 2023'
emoji = "💬"
text = '''Roy Ciampa noted CSB follows latest research for the term “touching” in 1 Corinthians 7. (I haven’t dug into how other modern translations compare in this area.)'''

[[thought]]
translation = "esv"
revision = "ESV 2016"
reference = "2 Corinthians 5:20"
date = '28 Jan 2025'
text = '''
Köstenberger, in *Salvation to the Ends* (2nd Ed, pg 169), points out that the ESV has, "we implore **you** on Christ's behalf,” (2 Cor 5:20) and the "you" is not in the Greek. In context, Paul seems to be referring to the world or people more broadly.

See CSB rendering which avoids this by making the "you" implicit, "We plead on Christ’s behalf, 'Be reconciled to God.'"
'''

[[thought]]
translation = "csb"
reference = "Galatians 4:6"
date = '1 Feb 2023'
emoji = "👍"
text = '''Footnote on Galatians 4:6 “other mss read your.” ESV doesn’t mention this textual variant.'''
